FIX:undefined variable type causes Segfault
Issue:https://gitee.com/openharmony/arkcompiler_ets_frontend/issues/IB2X66?from=project-issue

Description:
 arr = 1;
 Output is:
   TypeError: Unresolved reference arr [x.sts:1:1]
   Segmentation fault (core dumped)
 arr type undefined

Tests:
 ninja_tests(passed)
 parser tests(passed)

Signed-off-by:menjiaheng <menjiaheng@h-partners.com>